services:
  ddns:
    build: .
    container_name: ddns
    restart: always
    environment:
      - TZ=Asia/Kolkata
      - FREEDNS_TOKEN=${FREEDNS_TOKEN}
      - UPDATE_INTERVAL=${UPDATE_INTERVAL:-1}
    volumes:
      - dns-logs:/var/log/freedns
      - dns-config:/etc/freedns

volumes:
  dns-logs:
  dns-config:
